### 安装Numpy 

```bash
pip3 install numpy
```

In [1]:
import numpy as np

In [2]:
np_array = np.array([1,2,3,4,5])
np_array,type(np_array)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [3]:
# 整体加1
np_array_new = np_array + 1

In [4]:
np_array_new

array([2, 3, 4, 5, 6])

In [5]:
# 多维的
muti_np_array = np.array([[1,2,3],[4,5,6]])
muti_np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
muti_np_array.shape

(2, 3)

In [7]:
muti_np_array_ = np.array([[1,2],[3,4,5]])
muti_np_array_

array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [8]:
muti_np_array_.shape

(2,)