In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3]) #注意必须是相同的类型，否则会做类型向下转换
array,type(array)

(array([1, 2, 3]), numpy.ndarray)

In [3]:
# 数据类型
array.dtype

dtype('int64')

In [4]:
# Length of one array element in bytes.
array.itemsize  

8

In [5]:
# 里面有多少个元素
array.size 

3

In [6]:
# 结构
array.shape 

(3,)

In [7]:
# 维度
array.ndim

1

In [8]:
# 替换所有值
array.fill(0)
array

array([0, 0, 0])

In [9]:
# 数据类型
array.dtype

dtype('int64')

In [ ]:
# Length of one array element in bytes.
array.itemsize  

In [ ]:
# 里面有多少个元素
array.size 

In [ ]:
# 结构
array.shape 

In [ ]:
# 维度
array.ndim

In [ ]:
# 替换所有值
array.fill(0)
array

In [ ]:
# 索引和切片操作
array_new = np.array([1,2,3,4])
print(array_new[0])
print(array_new[::-1])

In [10]:
# 索引和切片操作
array_new = np.array([1,2,3,4])
print(array_new[0])
print(array_new[::-1])

8

In [11]:
# 里面有多少个元素
array.size 

3

In [12]:
# 结构
array.shape 

(3,)

In [13]:
# 维度
array.ndim

1

In [14]:
# 替换所有值
array.fill(0)
array

array([0, 0, 0])

In [15]:
# 索引和切片操作
array_new = np.array([1,2,3,4])
print(array_new[0])
print(array_new[::-1])

1
[4 3 2 1]
