In [1]:
import numpy as np

In [3]:
# 矩阵格式，多维的形式
array = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# 输出基本属性
print(array.size)
print(array.shape)
print(array.dtype)

9
(3, 3)
int64


In [4]:
# 取其中的一个值，按照（x,y）坐标的形式
array[1,1]

5

In [7]:
# 取某一行或者某一列所有的值
print(array[0,:]) #第一行，冒号就是切片的代表所有
print(array[:,0]) #第一列

[1 2 3]
[1 4 7]


In [9]:
# 取某一行或者某一列的的几个值，可以使用切片
print(array[1,0:2]) #取第二行的前两个值，行是固定的所以 x=1
print(array[0:2,0]) #取第一列的前两个值，列是固定的所以 y=0

[4 5]
[1 4]


In [12]:
# 深拷贝（避免对象引用同时修改）
"""演示引用同时修改的问题"""
array_new = array  # 此时array_new指向了array的引用，array_new修改其实就是修改了array
array_new[1,1] = 100
print(array_new)
print('-' * 18)
print(array)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]
------------------
[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]


In [14]:
array_new_copy = array.copy() #使用copy解决这个问题
print(array)
print('-' * 18)
print(array_new_copy)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]
------------------
[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]


In [15]:
array_new_copy[1,1] = 999   #可以看到已经不会影响原来的ndarray了
print(array)
print('-' * 18)
print(array_new_copy)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]
------------------
[[  1   2   3]
 [  4 999   6]
 [  7   8   9]]


In [17]:
# 生成随机
array_random = np.arange(0,100,10)
array_random

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
# 可以指定类型生成bool类型，可以使用这个东西当索引
mask = np.array([0,1,1,1,0,1,1,1,1,0],dtype=bool)  # >=1的是True，<=0是False
mask

array([False,  True,  True,  True, False,  True,  True,  True,  True,
       False])

In [21]:
# 使用上面的布尔类型做索引
array_random[mask]  # 可以发现结果集对应True的都保留了

array([10, 20, 30, 50, 60, 70, 80])

In [23]:
"""上面的结果有什么用？其实就是可以判断过滤数据的时候要不要这个值"""

In [25]:
# 生成0-1之间的随机数
random_array = np.random.rand(10) #生成10个
random_array

array([0.63387693, 0.2109806 , 0.56138125, 0.54359955, 0.31109633,
       0.55972276, 0.95097271, 0.42177654, 0.26841877, 0.99258474])

In [27]:
# 判断哪些大于 0.5
random_array > 0.5 #这个就会生成一个新的ndarray，dtype=bool

array([ True, False,  True,  True, False,  True,  True, False, False,
        True])

In [28]:
# 再根据这个结果筛选出大于0.5的结果集
random_array[random_array > 0.5]

array([0.63387693, 0.56138125, 0.54359955, 0.55972276, 0.95097271,
       0.99258474])

In [31]:
# 判断哪些位置的是符合我们条件的
np.where(random_array > 0.5)

(array([0, 2, 3, 5, 6, 9]),)

In [32]:
# 同样可以根据这些获取对应的数据
random_array[np.where(random_array > 0.5)]

array([0.63387693, 0.56138125, 0.54359955, 0.55972276, 0.95097271,
       0.99258474])

## 总结

ndarray 中除了可以传入普通数字索引外，还可以传入ndarray作为索引。如果传入的ndarray索引dtype=bool，那么会获得为True对应索引位置的值。
如果传入的dtype=int64，那么直接获得对应索引位置的值。