In [1]:
import numpy as np

In [ ]:
# 指定类型
array = np.array([1,2,3,4]) #默认的
array

In [ ]:
array_new = np.array([1,2,3,4],dtype=np.float32)
array_new

In [ ]:
# 什么类型都有的
array_mix = np.array([1,2.3,'str'])
array_mix

In [ ]:
array_mix_new = np.array([1,2.3,'str'],dtype=np.object)
array_mix_new

In [ ]:
array_mix_new * 2

In [ ]:
# 类型转换
array.dtype

In [ ]:
array_32 = array.astype(np.float32)  #这样就直接转换了

In [ ]:
array #但是对原始的是没影响的

In [ ]:
np.asarray(array,dtype=np.object) #这样也可以转换，也对原始的没影响

In [ ]:
array  

In [6]:
array  

[1 2 3 4]


In [7]:
array_new = np.array([1,2,3,4],dtype=np.float32)
array_new

array([1., 2., 3., 4.], dtype=float32)

In [8]:
# 什么类型都有的
array_mix = np.array([1,2.3,'str'])
array_mix

array(['1', '2.3', 'str'], dtype='<U32')

In [9]:
array_mix_new = np.array([1,2.3,'str'],dtype=np.object)
array_mix_new

array([1, 2.3, 'str'], dtype=object)

In [10]:
array_mix_new * 2

array([2, 4.6, 'strstr'], dtype=object)

In [12]:
# 类型转换
array.dtype

dtype('int64')

In [13]:
array_32 = array.astype(np.float32)  #这样就直接转换了

array([1., 2., 3., 4.], dtype=float32)

In [14]:
array #但是对原始的是没影响的

array([1, 2, 3, 4])

In [15]:
np.asarray(array,dtype=np.object) #这样也可以转换，也对原始的没影响

array([1, 2, 3, 4], dtype=object)

In [16]:
array  

array([1, 2, 3, 4])