In [1]:
import numpy as np

### array数组的数值计算

In [2]:
array = np.array([[0,1,3,4],
                  [4,5,2,7],
                  [8,1,10,10]],dtype=np.float32)
array

array([[ 0.,  1.,  3.,  4.],
       [ 4.,  5.,  2.,  7.],
       [ 8.,  1., 10., 10.]], dtype=float32)

In [3]:
array.shape

(3, 4)

In [4]:
array.ndim #有几个轴

2

In [5]:
# 求和
array.sum()

55.0

In [6]:
np.sum(array)

55.0

In [7]:
# 按照一定轴来求和，这里我理解的是因为它有2个轴（这个值其实就是表示第几个轴）
array.sum(axis=0)  #将x轴的求和就是竖着加

array([12.,  7., 15., 21.], dtype=float32)

In [8]:
array.sum(axis=1)

array([ 8., 18., 29.], dtype=float32)

In [9]:
# 求乘积
array.prod()

0.0

In [10]:
array.prod(axis = 0) #按y轴

array([  0.,   5.,  60., 280.], dtype=float32)

In [11]:
array.prod(axis=-1) #按最后一个轴，其实就是x轴进行相乘

array([  0., 280., 800.], dtype=float32)

In [12]:
# 求最大最小
array.max()

10.0

In [13]:
array.min()

0.0

In [14]:
array.max(axis = 0) #按照y轴求最大值

array([ 8.,  5., 10., 10.], dtype=float32)

In [15]:
# 求最大最小值所在的索引
array.argmin()

0

In [16]:
array.argmin(axis=0) #以行为维度找最小值，注意如果这个维度中有好几个最小值，那么它会返回最早的那个

array([0, 0, 1, 0])

In [17]:
array.argmin(axis=1) #以列为维度找最小值

array([0, 2, 1])

In [18]:
# 求平均值

In [19]:
array.mean()

4.5833335

In [20]:
array.mean(axis=0)

array([4.       , 2.3333333, 5.       , 7.       ], dtype=float32)

In [21]:
# 标准差
array.std()

3.328121

In [22]:
array.std(axis = 0)

array([3.2659864, 1.8856181, 3.5590262, 2.4494898], dtype=float32)

In [23]:
# 方差
array.var()

11.076389

In [24]:
array.var(axis=0)

array([10.666667 ,  3.5555556, 12.666667 ,  6.       ], dtype=float32)

In [25]:
# 做一个限制
array

array([[ 0.,  1.,  3.,  4.],
       [ 4.,  5.,  2.,  7.],
       [ 8.,  1., 10., 10.]], dtype=float32)

In [26]:
array.clip(3,6) #小于3的值都变为3，大于6的值都变为6

array([[3., 3., 3., 4.],
       [4., 5., 3., 6.],
       [6., 3., 6., 6.]], dtype=float32)

In [27]:
# 四舍五入
array_new = np.array([1.32,2.67,3.12])
array_new.round()

array([1., 3., 3.])

In [28]:
array_new.round(decimals=2) #保留小数后两位，所以没变化

array([1.32, 2.67, 3.12])

In [29]:
array_new.round(decimals=1)

array([1.3, 2.7, 3.1])

### 构造一个三维数组验证一下我们对axis的想法

In [30]:
array_muti = np.array([[[0,1,3,4,5],
                        [4,5,2,7,5],
                        [8,1,10,10,5]],
                       
                       [[0,1,3,4,5],
                       [4,5,2,7,5],
                       [8,1,10,10,5]]])

In [31]:
array_muti

array([[[ 0,  1,  3,  4,  5],
        [ 4,  5,  2,  7,  5],
        [ 8,  1, 10, 10,  5]],

       [[ 0,  1,  3,  4,  5],
        [ 4,  5,  2,  7,  5],
        [ 8,  1, 10, 10,  5]]])

In [32]:
array_muti.shape

(2, 3, 5)

In [33]:
array_muti.ndim 

3

In [34]:
array_muti.sum(axis=0)  

array([[ 0,  2,  6,  8, 10],
       [ 8, 10,  4, 14, 10],
       [16,  2, 20, 20, 10]])

In [35]:
array_muti.sum(axis=0).shape  #可以看出它的shape就是排除第一个维度之后的 (2, 3, 5) -> （3，5）

(3, 5)

In [36]:
array_muti.sum(axis=1)  

array([[12,  7, 15, 21, 15],
       [12,  7, 15, 21, 15]])

In [37]:
array_muti.sum(axis=1).shape #可以看出它的shape就是排除第二个维度之后的 (2, 3, 5) -> （2，5）

(2, 5)

In [38]:
array_muti.sum(axis=2)  #这个就不展示了，显然结果是 （2，3）

array([[13, 23, 34],
       [13, 23, 34]])

### 总结

其中axis={shape.index}，如果原始ndarray的shape=(2,3,5)，那么array.sum(axis=0) 得到的结果就是一个shape=(3,5)的结果集；array.sum(axis=1) 得到的结果是一个shape=(2,5)的结果集。