In [1]:
import numpy as np

In [2]:
array = np.array([[7,8,3],
                  [14,5,6]])
array

array([[ 7,  8,  3],
       [14,  5,  6]])

### 按照轴排序

In [3]:
np.sort(array) #默认是以最后一个轴排的序

array([[ 3,  7,  8],
       [ 5,  6, 14]])

In [4]:
np.sort(array,axis=0) #对每列进行排序

array([[ 7,  5,  3],
       [14,  8,  6]])

In [5]:
np.sort(array,axis=1) #对每行进行排序

array([[ 3,  7,  8],
       [ 5,  6, 14]])

### 获得排序的索引

In [6]:
"""
这个是啥意思？就是你这么排序，7，8，3 -> 3，7，8  得到的是之前元素所在的索引，也就是2，0，1
原来在2索引的元素现在过来啦
"""
np.argsort(array,axis=1) 

array([[2, 0, 1],
       [1, 2, 0]])

### 获取已存在顺序列表中需要插入新元素的索引

In [7]:
array_new = np.linspace(0,100,5) #生成一个等差数列
array_new

array([  0.,  25.,  50.,  75., 100.])

In [8]:
insert_values = np.array([1,55])  #待插入的值
"""
注意这个array_new必须是排序好之后的数组才可以使用
"""
np.searchsorted(array_new,insert_values)  #得到的结果就是这些需要插入的值，需要插入原ndarry的索引位置

array([1, 3])

### 特殊的排序（到时候再研究吧）

In [ ]:
"""想要实现的效果，第三列升序，第一列降序"""
array_new = np.array([[1,0,6],
                      [1,7,0],
                      [2,3,1],
                      [2,4,0]])
array_new

In [ ]:
index = np.lexsort([-1 *array_new[:,0],array_new[:,2]])  
index

In [ ]:
array_new = array_new[index]
array_new

In [9]:
array_new = array_new[index]
array_new

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [10]:
index = np.lexsort([-1 *array_new[:,0],array_new[:,2]])  
index

array([3, 1, 2, 0])

In [11]:
array_new = array_new[index]
array_new

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])