In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3,4],
                [4,5,6,6],
                [5,7,4,2]])
array

array([[1, 2, 3, 4],
       [4, 5, 6, 6],
       [5, 7, 4, 2]])

In [3]:
array.shape

(3, 4)

### 改变shape

大小必须不能改变

In [4]:
# 直接修改
array.shape = 4,3

In [5]:
array

array([[1, 2, 3],
       [4, 4, 5],
       [6, 6, 5],
       [7, 4, 2]])

In [6]:
# 使用reshape
array.reshape(2,6)

array([[1, 2, 3, 4, 4, 5],
       [6, 6, 5, 7, 4, 2]])

### 增加维度（轴）

In [7]:
array_new = np.arange(10)
array_new

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array_new_axis_b = array_new[np.newaxis,:] #增加了维度
array_new_axis_b

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
array_new_axis_b.shape

(1, 10)

In [10]:
# 也可以以另外一个维度进行增加
array_new_axis_l = array_new[:,np.newaxis] #增加了维度
array_new_axis_l

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
array_new_axis_l.shape

(10, 1)

### 压缩（把没用的轴去掉）

In [12]:
array_new_axis_l.squeeze()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 转置（行转列/列转行）

In [13]:
array_new_axis_l

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [14]:
array_new_axis_l.transpose() #都可以，不会修改原来的ndarray

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
array_new_axis_l.T #都可以，不会修改原来的ndarray

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 数组的连接

In [16]:
a = np.array([[1,2,3],
             [4,22,4],
             [2,4,5]])
a

array([[ 1,  2,  3],
       [ 4, 22,  4],
       [ 2,  4,  5]])

In [17]:
b = np.array([[61,2,3],
             [41,22,4],
             [21,4,15]])
b

array([[61,  2,  3],
       [41, 22,  4],
       [21,  4, 15]])

In [18]:
c = np.concatenate((a,b)) 
c

array([[ 1,  2,  3],
       [ 4, 22,  4],
       [ 2,  4,  5],
       [61,  2,  3],
       [41, 22,  4],
       [21,  4, 15]])

In [19]:
c.shape

(6, 3)

In [20]:
# 也可以指定轴
d = np.concatenate((a,b),axis=1)
d

array([[ 1,  2,  3, 61,  2,  3],
       [ 4, 22,  4, 41, 22,  4],
       [ 2,  4,  5, 21,  4, 15]])

In [21]:
d.shape

(3, 6)

In [22]:
np.vstack((a,b))  #垂直按行拼

array([[ 1,  2,  3],
       [ 4, 22,  4],
       [ 2,  4,  5],
       [61,  2,  3],
       [41, 22,  4],
       [21,  4, 15]])

In [23]:
np.hstack((a,b))  #按列拼

array([[ 1,  2,  3, 61,  2,  3],
       [ 4, 22,  4, 41, 22,  4],
       [ 2,  4,  5, 21,  4, 15]])

### 拉平

In [24]:
a

array([[ 1,  2,  3],
       [ 4, 22,  4],
       [ 2,  4,  5]])

In [25]:
a.flatten()  #都可以不影响原始数组

array([ 1,  2,  3,  4, 22,  4,  2,  4,  5])

In [26]:
a.ravel() #都可以不影响原始数组

array([ 1,  2,  3,  4, 22,  4,  2,  4,  5])