In [1]:
import numpy as np

In [2]:
# 生成
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array = np.arange(0,10,2)
array

array([0, 2, 4, 6, 8])

In [4]:
array = np.arange(0,10,2,dtype=np.float32)
array

array([0., 2., 4., 6., 8.], dtype=float32)

In [5]:
# 等差数列
array_new = np.linspace(0,10,10)
array_new

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [6]:
# 以10为底的 ? 这个函数先记下，以后再说
np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [7]:
# 二维网格，类似坐标系
"""生成了5个X坐标，3个Y坐标，所以可以在坐标系中画出15个点"""
x = np.arange(0,10,2)
x

array([0, 2, 4, 6, 8])

In [8]:
y = np.arange(0,9,3)
y

array([0, 3, 6])

In [9]:
x,y = np.meshgrid(x,y)
x

array([[0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [10]:
y

array([[0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3],
       [6, 6, 6, 6, 6]])