In [1]:
import numpy as np

In [ ]:
x = np.array([5,5])
y = np.array([2,2])

In [ ]:
# 乘法
"""可以看出就是对应位置相乘"""
a = np.multiply(x,y)
a

In [ ]:
a.shape

In [ ]:
# 这种乘法就是对应位置求和以后再加起来
b = np.dot(x,y)
b

In [ ]:
# 对应位置是否相等
e = np.array([1,2,3,1])
f = np.array([0,1,1,1])

In [ ]:
f == e

In [ ]:
# 逻辑与，如果都是真则真，>=1真 ，<=-假
np.logical_and(f,e)  

In [ ]:
# 逻辑或，一个为真则真
np.logical_or(f,e)

In [ ]:
# 逻辑非
np.logical_not(f,e)

In [2]:
# 逻辑非
np.logical_not(f,e)

In [3]:
# 乘法
"""可以看出就是对应位置相乘"""
a = np.multiply(x,y)
a

array([10, 10])

In [4]:
a.shape

(2,)

In [5]:
# 这种乘法就是对应位置求和以后再加起来
b = np.dot(x,y)
b

20

In [6]:
# 对应位置是否相等
e = np.array([1,2,3,1])
f = np.array([0,1,1,1])

In [7]:
f == e

array([False, False, False,  True])

In [8]:
# 逻辑与，如果都是真则真，>=1真 ，<=-假
np.logical_and(f,e)  

array([False,  True,  True,  True])

In [9]:
# 逻辑或，一个为真则真
np.logical_or(f,e)

array([ True,  True,  True,  True])

In [10]:
# 逻辑非
np.logical_not(f,e)

array([1, 0, 0, 0])