In [1]:
import numpy as np

In [ ]:
np.random.rand(3,2) #float 0-1之间

In [ ]:
np.random.randint(10,size = (5,4)) #随机整数 0-9之间

In [ ]:
np.random.rand() #float 0-1之间 设置精度也不会改变它的长度

In [ ]:
np.random.randint(0,10,3) #在0-9之间取3个数

In [ ]:
# 高斯分布
mu,sigma = 0,0.1
np.random.normal(mu,sigma,10)

In [ ]:
# 修改精度，注意对下面这个无效
np.set_printoptions(precision=2)
np.random.rand()

In [ ]:
np.random.normal(mu,sigma,10) #对这些有效

In [ ]:
# 洗牌（重新打乱顺序）
array = np.arange(10)
array

In [ ]:
np.random.shuffle(array)

In [ ]:
array

In [ ]:
# 随机种子，指定了种子以后，下次的随机不管执行多少次结果都是一样的。注意：每次随机都需要重新指定种子
np.random.seed(0)
np.random.rand(3,2)

In [2]:
# 随机种子，指定了种子以后，下次的随机不管执行多少次结果都是一样的。注意：每次随机都需要重新指定种子
np.random.seed(0)
np.random.rand(3,2)

array([[0.93951228, 0.41711654],
       [0.10793965, 0.54281223],
       [0.10340104, 0.51207865]])

In [3]:
np.random.randint(10,size = (5,4)) #随机整数 0-9之间

array([[9, 8, 1, 9],
       [6, 4, 1, 8],
       [0, 6, 7, 7],
       [8, 8, 5, 7],
       [8, 7, 2, 0]])

In [4]:
np.random.rand() #float 0-1之间 设置精度也不会改变它的长度

0.48024809465238627

In [5]:
np.random.randint(0,10,3) #在0-9之间取3个数

array([5, 6, 9])

In [6]:
# 高斯分布
mu,sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.12907271,  0.02242102,  0.08617581, -0.19220717,  0.16032589,
        0.03144464, -0.01658415, -0.11567827, -0.03160486,  0.06595287])

In [7]:
# 修改精度，注意对下面这个无效
np.set_printoptions(precision=2)
np.random.rand()

0.2319195862392921

In [8]:
np.random.normal(mu,sigma,10) #对这些有效

array([-0.05,  0.03,  0.13, -0.  ,  0.05, -0.01,  0.05,  0.03, -0.07,
        0.14])

In [9]:
# 洗牌（重新打乱顺序）
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.random.shuffle(array)

In [11]:
array

array([8, 4, 3, 6, 5, 9, 7, 0, 2, 1])

In [12]:
# 随机种子，指定了种子以后，下次的随机不管执行多少次结果都是一样的。注意：每次随机都需要重新指定种子
np.random.seed(0)
np.random.rand(3,2)

array([[0.55, 0.72],
       [0.6 , 0.54],
       [0.42, 0.65]])