In [1]:
import numpy as np

In [2]:
np.random.rand(3,2) #float 0-1之间

array([[0.26426412, 0.61084335],
       [0.3845251 , 0.58451358],
       [0.66832083, 0.39140079]])

In [3]:
np.random.randint(10,size = (5,4)) #随机整数 0-9之间

array([[2, 7, 5, 2],
       [7, 4, 9, 7],
       [0, 8, 7, 0],
       [4, 8, 5, 0],
       [5, 1, 9, 2]])

In [4]:
np.random.rand() #float 0-1之间 设置精度也不会改变它的长度

0.17158017983589113

In [5]:
np.random.randint(0,10,3) #在0-9之间取3个数

array([7, 2, 9])

In [6]:
# 高斯分布
mu,sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([ 0.17070138, -0.05609879, -0.11044104, -0.11792193,  0.08882555,
        0.00777668,  0.0890701 ,  0.01957408, -0.00041659, -0.12902009])

In [7]:
# 修改精度，注意对下面这个无效
np.set_printoptions(precision=2)
np.random.rand()

0.5074629404168871

In [8]:
np.random.normal(mu,sigma,10) #对这些有效

array([ 0.05, -0.15, -0.18, -0.09,  0.06, -0.01, -0.16,  0.13,  0.07,
       -0.13])

In [9]:
# 洗牌（重新打乱顺序）
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.random.shuffle(array)

In [11]:
array

array([7, 8, 6, 3, 5, 9, 2, 1, 0, 4])

In [12]:
# 随机种子，指定了种子以后，下次的随机不管执行多少次结果都是一样的。注意：每次随机都需要重新指定种子
np.random.seed(0)
np.random.rand(3,2)

array([[0.55, 0.72],
       [0.6 , 0.54],
       [0.42, 0.65]])