In [1]:
import numpy as np

### 保存txt

In [2]:
array = np.array([[1,2,3],
                 [4,5,6]])
np.savetxt('save1.txt',array) #这样是科学计数法

In [3]:
np.savetxt('save2.txt',array,fmt='%d',delimiter=',')

In [4]:
np.savetxt('save3.txt',array,fmt='%.2f',delimiter=',')

### 读写array数据

In [5]:
np.save('test.npy',array)

In [6]:
np.load('test.npy')

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 批量保存，其实是个压缩包 a.npy   b.npy
np.savez('test.npz',a = np.arange(10),b = np.arange(5))

In [8]:
data = np.load('test.npz')

In [9]:
data['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
data['b']

array([0, 1, 2, 3, 4])